DROP TABLE IF EXISTS Alarms;
DROP TABLE IF EXISTS Measurements;
DROP TABLE IF EXISTS Sensors;
DROP TABLE IF EXISTS Limits;
DROP TABLE IF EXISTS alarms;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS sensors;
DROP TABLE IF EXISTS limits;